const defaultExercises = [
  'Alternating Dumbbell Curl',
  'Arnold Press',
  'Barbell Curl',
  'Barbell Rows',
  'Barbell Rows (Smith Machine)',
  'Bench Press (Barbell)',
  'Bench Press (Dumbbell)',
  'Bench Press (Smith Machine)',
  'Bent Over Dumbbell Row',
  'Box Squat (Barbell)',
  'Bulgarian Split Squat',
  'Burpee',
  'Cable Crossover',
  'Calf Raise (Leg Press)',
  'Calf Raise (Sitting)',
  'Calf Raise (Standing)',
  'Cycling',
  'Deadlift',
  'Decline Bench Press (Barbell)',
  'Decline Bench Press (Dumbbell)',
  'Decline Bench Press (Smith Machine)',
  'Hack Squat',
  'Incline Bench Press (Barbell)',
  'Incline Bench Press (Dumbbell)',
  'Incline Bench Press (Smith Machine)',
  'Lateral Raises',
  'Lat Pulldown (Close Grip)',
  'Lat Pulldown (Neutral Grip)',
  'Lat Pulldown (Reverse Grip)',
  'Lat Pulldown (Straight Arm)',
  'Lat Pulldown (Wide Grip)',
  'Leg Extension',
  'Leg Press',
  'Lying Leg Curl',
  'Overhead Press (Barbell)',
  'Overhead Press (Dumbbell)',
  'Overhead Press (Smith Machine)',
  'Preacher Curl (EZ Bar)',
  'Preacher Curl (Single Arm)',
  'Pull-Ups',
  'Rowing Machine',
  'Running',
  'Seated Cable Row',
  'Seated Cable Row (Close Grip)',
  'Seated Cable Row (Reverse Grip)',
  'Seated Cable Row (Wide Grip)',
  'Seated Leg Curl',
  'Single Arm Bent Over Row (Dumbbell)',
  'Single Arm Preacher Curl',
  'Single Arm Seated Cable Row',
  'Squat (Barbell)',
  'Stairmaster',
  'Tricep Extensions (Bar)',
  'Tricep Extensions (Rope)',
  'Tricep Extensions (V-Bar)',
  'Tricep Pushdown (Bar)',
  'Tricep Pushdown (Rope)',
  'Tricep Pushdown (V-Bar)',
];

export default defaultExercises;
