const defaultExercises = [
  'Alternating Dumbbell Curl',
  'Arnold Press',
  'Barbell Curl',
  'Barbell Rows',
  'Barbell Rows (Smith Machine)',
  'Bench Press (Barbell)',
  'Bench Press (Dumbbell)',
  'Bench Press (Smith Machine)',
  'Bent Over Dumbbell Row',
  'Box Squat (Barbell)',
  'Squats',
  'Bulgarian Split Squat (Dumbbell)',
  'Bulgarian Split Squat (Barbell)',
  'Burpee',
  'Cable Crossover',
  'Calf Raise (Leg Press)',
  'Calf Raise (Sitting)',
  'Calf Raise (Standing)',
  'Cycling',
  'Decline Bench Press (Barbell)',
  'Decline Bench Press (Dumbbell)',
  'Decline Bench Press (Smith Machine)',
  'Hack Squat',
  'Incline Bench Press (Barbell)',
  'Incline Bench Press (Dumbbell)',
  'Incline Bench Press (Smith Machine)',
  'Lateral Raises (Cable)',
  'Lateral Raises (Dumbbell)',
  'Lat Pulldown (Close Grip)',
  'Lat Pulldown (Neutral Grip)',
  'Lat Pulldown (Reverse Grip)',
  'Lat Pulldown (Straight Arm)',
  'Lat Pulldown (Wide Grip)',
  'Leg Extension',
  'Leg Press',
  'Lying Leg Curl',
  'Overhead Press (Barbell)',
  'Overhead Press (Dumbbell)',
  'Overhead Press (Smith Machine)',
  'Preacher Curl (EZ Bar)',
  'Preacher Curl (Single Arm)',
  'Pull-Ups',
  'Pull-Ups (Wide Grip)',
  'Rowing Machine',
  'Outdoor Running',
  'Indoor Running',
  'Seated Cable Row (Neutral Grip)',
  'Seated Cable Row (Close Grip)',
  'Seated Cable Row (Reverse Grip)',
  'Seated Cable Row (Wide Grip)',
  'Seated Leg Curl',
  'Single Arm Bent Over Row (Dumbbell)',
  'Single Arm Preacher Curl',
  'Single Arm Seated Cable Row',
  'Squat (Barbell)',
  'Stairmaster',
  'Tricep Extensions (Bar)',
  'Tricep Extensions (Rope)',
  'Tricep Extensions (V-Bar)',
  'Tricep Pushdown (Bar)',
  'Tricep Pushdown (Rope)',
  'Tricep Pushdown (V-Bar)',
  'Chest Fly (Cable)',
  'Chest Fly (Machine)',
  'Push-Up',
  'Incline Chest Fly (Dumbbell)',
  'Decline Chest Fly (Dumbbell)',
  'T-Bar Row (Barbell)',
  'T-Bar Row (Machine)',
  'Pull-Up (Neutral Grip)',
  'Pull-Up (Wide Grip)',
  'Chin-Up (Underhand Grip)',
  'Front Raise (Dumbbell)',
  'Front Raise (Barbell)',
  'Upright Row (Barbell)',
  'Upright Row (EZ Bar)',
  'Concentration Curl (Dumbbell)',
  'Drag Curl (Barbell)',
  'Spider Curl (EZ Bar)',
  'Hammer Curl (Dumbbell)',
  'Overhead Tricep Extension (Dumbbell)',
  'Overhead Tricep Extension (EZ Bar)',
  'Skullcrusher (EZ Bar)',
  'Romanian Deadlift (Barbell)',
  'Romanian Deadlift (Dumbbell)',
  'Leg Curl (Standing)',
  'Step Up (Barbell)',
  'Step Up (Dumbbell)',
  'Glute Kickback (Cable)',
  'Hip Thrust (Barbell)',
  'Sumo Deadlift (Barbell)',
  'Sumo Squat (Dumbbell)',
  'Plank',
  'Crunch (Bodyweight)',
  'Crunch (Cable)',
  'Leg Raise (Hanging)',
  'Leg Raise (Lying)',
  'Russian Twist (Bodyweight)',
  'Elliptical',
  'Treadmill Walk',
  'Treadmill Run',
  'Sled Push',
  'Battle Ropes',
  'Chest Press (Machine)',
  'Chest Press (Cable)',
  'Chest Dip (Bodyweight)',
  'Incline Chest Press (Machine)',
  'Decline Chest Press (Machine)',
  'Pull-Over (Cable)',
  'Pull-Over (Dumbbell)',
  'Back Extension (Machine)',
  'Inverted Row (Bodyweight)',
  'One Arm T-Bar Row',
  'Cable Row (Single Arm)',
  'Lat Pulldown (Behind the Neck)',
  'Chin-Up (Weighted)',
  'Shoulder Press (Machine)',
  'Shoulder Press (Cable)',
  'Reverse Fly (Cable)',
  'Reverse Fly (Machine)',
  'Face Pull (Rope)',
  'Lateral Raise (Cable)',
  'Lateral Raise (Machine)',
  'Front Raise (Cable)',
  'Shrug (Dumbbell)',
  'Shrug (Barbell)',
  'Cable Curl (Bar)',
  'Cable Curl (Rope)',
  'Zottman Curl (Dumbbell)',
  'Incline Curl (Dumbbell)',
  'Cross Body Curl (Dumbbell)',
  'Preacher Curl (Machine)',
  'Spider Curl (Dumbbell)',
  'Kickback (Dumbbell)',
  'Kickback (Cable)',
  'Tricep Dip (Bodyweight)',
  'Tricep Dip (Bench)',
  'Overhead Tricep Extension (Cable)',
  'Tricep Pushdown (Straight Bar)',
  'Leg Curl (Machine)',
  'Hip Abduction (Machine)',
  'Hip Adduction (Machine)',
  'Walking Lunge (Barbell)',
  'Walking Lunge (Dumbbell)',
  'Good Morning (Barbell)',
  'Step Up (Bodyweight)',
  'Split Squat (Dumbbell)',
  'Lunge (Dumbbell)',
  'Lunge (Barbell)',
  'Smith Machine Squat',
  'Front Squat (Barbell)',
  'Pistol Squat (Bodyweight)',
  'Glute Bridge (Barbell)',
  'Cable Pull Through',
  'Hip Thrust (Machine)',
  'Reverse Lunge (Barbell)',
  'Reverse Lunge (Dumbbell)',
  'Donkey Calf Raise',
  'Calf Press (Leg Press Machine)',
  'Cable Woodchopper (High to Low)',
  'Cable Woodchopper (Low to High)',
  'Mountain Climbers',
  'V-Ups',
  'Toe Touches',
  'Seated Ab Crunch (Machine)',
  'Sit-Up (Weighted)',
  'Sit-Up',
  'Side Plank',
  'Plank with Shoulder Tap',
  'Plank to Push-Up',
  'Farmer Carry (Dumbbell)',
  'Farmer Carry (Kettlebell)',
  'Jump Squat (Bodyweight)',
  'Medicine Ball Slam',
  'Box Jump',
  'Bear Crawl',
  'Wall Ball (Medicine Ball)',
  'Kettlebell Swing',
  'Battle Ropes (Alternating)',
  'Sled Pull',
  'Stair Run',
  'High Knees',
  'Jumping Jacks',
  'Shadow Boxing',
  'Rowing Sprint',
  'Outdoor Walk',
  'Outdoor Run',
  'Run',
  'Walk',
  'Biking (Spin Bike)',
  'Air Bike Sprint',
  'VR Gaming',
];

export default defaultExercises;
